### ISSUE TITLE
Site displays Magenta. Magenta is toally purple

### ISSUE THREAD

**Issue by corlinp** [VaughnGH/notpurple#2]

**Comment by JeffAbrahamson** [comment]
Please see [FAQ](http://www.purple.com/faq.html) item 5.

**Comment by TangentFoxy** [comment]
D:

**Comment by VaughnGH** [comment]
I am happy to report that commit 02fcdfc84e89fd73fbd638ece5543fd861961a0f has removed the instance of this traitor. Your vigilance is appreciated.
