### ISSUE TITLE
Indicate commits with six character hashs

### ISSUE THREAD

**Issue by JeffAbrahamson** [VaughnGH/notpurple#3]
Git is perfectly happy with six characters to represent a commit, as much as if one uses seven.  But six is also interpretable as an RGB colour.  This seems somehow appropriate.

More important, avoid commits that thus represent colours close to the colour purple.  A commit starting 7d26cd, for example, would be a sign that something is wrong in the code.

**Comment by VaughnGH** [comment]
That would be true, however NotPurple formally denies the existence of any hexadecimal color representation. Nice try.
